version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/plateforme-administ-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:  Mously1@
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-react
    ports:
      - "3000:80"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mously1@
      MYSQL_DATABASE: plateforme-administ-db
    ports:
      -  "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
