name: CI-CD  Build and Test Frontend & Backend

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build-frontend:
    name: Build Frontend (React)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend-react
        run: npm install

      - name: Run tests (if any)
        working-directory: frontend-react
        run: npm test --if-present

      - name: Build project
        working-directory: frontend-react
        run: npm run build

  build-backend:
    name: Build Backend (Spring Boot)
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        working-directory: backend
        run: chmod +x ./gradlew

      - name: Build with Gradle
        working-directory: backend
        run: ./gradlew build

      - name: Run tests
        working-directory: backend
        run: ./gradlew test
