name: CI - Frontend & Backend Tests

on:
  push:
    branches:
      - main
      - frontend
      - backend
  pull_request:
    branches:
      - main
      - frontend
      - backend

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3
        with:
          path: frontend

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies and run tests (frontend)
        working-directory: frontend
        run: |
          npm install
          npm test -- --watchAll=false

  backend-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3
        with:
          path: backend

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run backend tests with Gradle
        working-directory: backend
        run: ./gradlew test
